version: 2

sources:
  - name: staging
    database: dwh_db_name
    schema: data_raw
    tags: ["raw"]

    tables:
      - name: cook_county_parcel_sales      
      - name: cook_county_parcel_locations      
      - name: cook_county_neighborhood_boundaries

      - name: temp_cook_county_parcel_sales
      - name: temp_cook_county_parcel_locations
      - name: temp_cook_county_neighborhood_boundaries